### ISSUE TITLE
Failure against Ubuntu bionic

### ISSUE THREAD

**Issue by ageis** [geerlingguy/ansible-role-mysql#420]
```TASK [ansible-role-mysql : Remove MySQL test database.] ***********************************************************************************************************************************************************
Wednesday 18 November 2020  10:59:37 -0800 (0:00:00.021)       0:06:13.874 ****
Wednesday 18 November 2020  10:59:37 -0800 (0:00:00.021)       0:06:13.874 ****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'tuple' object has no attribute 'execute'
fatal: [db]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_mysql_db_payload_zhtfhx2i/ansible_mysql_db_payload.zip/ansible/modules/database/mysql/mysql_db.py\", line 456, in <module>\n  File \"/tmp/ansible_mysql_db_payload_zhtfhx2i/ansible_mysql_db_payload.zip/ansible/modules/database/mysql/mysql_db.py\", line 400, in main\n  File \"/tmp/ansible_mysql_db_payload_zhtfhx2i/ansible_mysql_db_payload.zip/ansible/modules/database/mysql/mysql_db.py\", line 173, in db_exists\nAttributeError: 'tuple' object has no attribute 'execute'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Does this role work only on Python 3.7, or is it meant for 2.7?

**Comment by ageis** [comment]
Got this to work with Ansible 2.10.3 and release tag 3.3.0.
